-- Idempotent PostgreSQL 16 upgrade for volumes created with the first-stage schema.
-- Run after the database is healthy and before starting a new backend version.
-- Keep schema.sql for empty-volume initialization; it does not alter existing tables.
BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS shop_address VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS recipient_phone VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_deadline TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS rider_id BIGINT;

-- The old address was the delivery-address snapshot; preserve it in the new field.
UPDATE orders SET delivery_address = address
WHERE delivery_address IS NULL AND address IS NOT NULL;

CREATE TABLE IF NOT EXISTS business_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    default_category BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS cart_delivery_info (
    user_id BIGINT NOT NULL REFERENCES users(id),
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    recipient_name VARCHAR(50) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, shop_id)
);
CREATE TABLE IF NOT EXISTS administrators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password_hash VARCHAR(60) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS riders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_name VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(60) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS refund_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    reason VARCHAR(255) NOT NULL,
    evidence_urls VARCHAR(1000),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    created_at TIMESTAMP NOT NULL,
    handled_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- 店铺营业时间与店铺经营品类关联；已有数据卷不会重跑 schema.sql 的 CREATE TABLE，故在此补。
ALTER TABLE shops ADD COLUMN IF NOT EXISTS opening_time TIME;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS closing_time TIME;

CREATE TABLE IF NOT EXISTS shop_business_categories (
    shop_id BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    business_category_id BIGINT NOT NULL REFERENCES business_categories(id),
    PRIMARY KEY (shop_id, business_category_id)
);

-- 店铺推荐的偏好信号：顾客搜索关键词历史（注销账号时随之删除）
CREATE TABLE IF NOT EXISTS user_search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    keyword VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_search_history_user
    ON user_search_history(user_id, created_at DESC);

-- 按经营范围名称把已有店铺补进经营品类关联表，否则新表为空、按品类筛选恒为空。
-- 只做精确匹配，不做相似度猜测；匹配不上的店铺由商家在商家信息页自行选择品类。
INSERT INTO shop_business_categories(shop_id, business_category_id)
SELECT sh.id, bc.id
FROM shops sh
JOIN merchants m ON m.id = sh.merchant_id
JOIN business_categories bc ON bc.name = m.business_scope
ON CONFLICT DO NOTHING;

COMMIT;
